spring.application.name=appmovie


spring.application.name=appmovie

server.port=8181

# ==============================
# CognoDB Connection
# ==============================
cognodb.uri=bolt+s://db-10ca8d36.bravo.databases.cognodb.com
cognodb.username=cognodb

cognodb.password=c0db6063527c9d8eed4237cdbed32e7d
